name: ubuntu-selenium-python

on:
  push:
    paths:
      - 'selenium-python/**'
      - '.github/workflows/ubuntu-selenium-python.yml'
  pull_request:
    paths:
      - 'selenium-python/**'
      - '.github/workflows/ubuntu-selenium-python.yml'

defaults:
  run:
    working-directory: selenium-python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r selenium-python/requirements.txt

    - name: Run tests
      working-directory: ./selenium-python
      run: pytest -v test.py

    - name: Dump log
      if: always()
      working-directory: ./selenium-python
      run: cat chromedriver.log
